/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

void button1_Click1(GButton button) { //_CODE_:button1:709609:
  println("button1 - GButton event occured " + System.currentTimeMillis()%10000000 );
} //_CODE_:button1:709609:



// Create all the GUI controls. 
// autogenerated do not edit
void createGUI(){
  G4P.setColorScheme(this, GCScheme.BLUE_SCHEME);
  G4P.messagesEnabled(false);
  button1 = new GButton(this, "Face text", 367, 262, 80, 30);
  button1.setTextAlign(GAlign.CENTER | GAlign.MIDDLE);
  button1.addEventHandler(this, "button1_Click1");
}

// Variable declarations 
// autogenerated do not edit
GButton button1; 

